spring:
  application:
    name: MessagesBestPractice
    
server:
 port: 9090
 
quote : Be the change you wish to see in the world..!
advice : Stay curious, keep learning...!
 
app:
  messages:
   wlcmMessage : Welcome To My Application..!
   greetMessage : Good Morning Mr Developer..!
  
